In [25]:
import numpy as np

In [26]:
# Read input
filename = 'input.txt'
#filename = 'test1.txt'
with open(filename) as f:
    input = f.read().replace('/n', '')
integers = np.asarray(input.split(',')).astype(int)

# Part 1

In [27]:
# Convert input for part 1
if filename == 'input.txt':
    integers[1] = 12
    integers[2] = 2
integers

array([  1,  12,   2,   3,   1,   1,   2,   3,   1,   3,   4,   3,   1,
         5,   0,   3,   2,   1,   9,  19,   1,  19,   5,  23,   2,  23,
        13,  27,   1,  10,  27,  31,   2,  31,   6,  35,   1,   5,  35,
        39,   1,  39,  10,  43,   2,   9,  43,  47,   1,  47,   5,  51,
         2,  51,   9,  55,   1,  13,  55,  59,   1,  13,  59,  63,   1,
         6,  63,  67,   2,  13,  67,  71,   1,  10,  71,  75,   2,  13,
        75,  79,   1,   5,  79,  83,   2,  83,   9,  87,   2,  87,  13,
        91,   1,  91,   5,  95,   2,   9,  95,  99,   1,  99,   5, 103,
         1,   2, 103, 107,   1,  10, 107,   0,  99,   2,  14,   0,   0])

In [28]:
i = 0
op_code = integers[i]
while op_code != 99:
    a = integers[integers[i+1]]
    b = integers[integers[i+2]]
    output_pos = integers[i+3]
    if op_code == 1:
        output = a + b
    elif op_code == 2:
        output = a * b
    else:
        raise Exception('Invalid op_code supplied')
    integers[output_pos] = output
    i += 4
    op_code = integers[i]

In [29]:
integers

array([3895705,      12,       2,       2,       1,       1,       2,
             3,       1,       3,       4,       3,       1,       5,
             0,       3,       2,       1,       9,      36,       1,
            19,       5,      37,       2,      23,      13,     185,
             1,      10,      27,     189,       2,      31,       6,
           378,       1,       5,      35,     379,       1,      39,
            10,     383,       2,       9,      43,    1149,       1,
            47,       5,    1150,       2,      51,       9,    3450,
             1,      13,      55,    3455,       1,      13,      59,
          3460,       1,       6,      63,    3462,       2,      13,
            67,   17310,       1,      10,      71,   17314,       2,
            13,      75,   86570,       1,       5,      79,   86571,
             2,      83,       9,  259713,       2,      87,      13,
       1298565,       1,      91,       5, 1298566,       2,       9,
            95, 3895

# Part 2

In [44]:
# Read input
filename = 'input.txt'
#filename = 'test1.txt'
with open(filename) as f:
    input = f.read().replace('/n', '')
integers_original = np.asarray(input.split(',')).astype(int)

In [41]:
target = 19690720
max_value = 99
grid_search = np.zeros(shape=(max_value,max_value)).astype(bool)

In [69]:
def find_target(noun:int, verb:int):
    integers = integers_original.copy()
    integers[1] = noun
    integers[2] = verb
    i = 0
    op_code = integers[i]
    while op_code != 99:
        a = integers[integers[i+1]]
        b = integers[integers[i+2]]
        output_pos = integers[i+3]
        if op_code == 1:
            output = a + b
        elif op_code == 2:
            output = a * b
        else:
            raise Exception('Invalid op_code supplied')
        integers[output_pos] = output
        i += 4
        op_code = integers[i]
    return integers[0] == target

In [70]:
for x in range(max_value):
    for y in range(max_value):
        grid_search[x][y] = find_target(x, y)

In [75]:
result = np.argwhere(grid_search)
result

array([[64, 17]])

In [79]:
100 * result[0][0] + result[0][1]

6417